default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres_user
  password: tvtM#3WC&x%E

development:
  <<: *default
  database: airbnb_clone_development

test:
  <<: *default
  database: airbnb_clone_test

production:
  <<: *default
  database: airbnb_clone_production
  username: postgres_user
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
